import type { SKU, Competitor, AgentRun, Recommendation, EmailAlert, AgentLog, CompetitorCheck, DashboardStats } from '@/types'

export const mockCompetitors: Competitor[] = [
  {
    id: 'comp-1',
    name: 'Jumbo',
    website_url: 'https://www.jumbo.com',
    search_url_pattern: 'https://www.jumbo.com/en/search?q={query}',
    logo: '🛒',
    matching_rules: { title_similarity_threshold: 0.75, brand_match_required: true, model_match_required: false },
    price_selector: '.product-price .price',
    screenshot_required: true,
    status: 'active',
    created_at: '2025-01-10T08:00:00Z',
    updated_at: '2025-01-10T08:00:00Z',
  },
  {
    id: 'comp-2',
    name: 'Sharaf DG',
    website_url: 'https://www.sharafdg.com',
    search_url_pattern: 'https://www.sharafdg.com/search?q={query}',
    logo: '🔌',
    matching_rules: { title_similarity_threshold: 0.80, brand_match_required: true, model_match_required: true },
    price_selector: '.price-current',
    screenshot_required: true,
    status: 'active',
    created_at: '2025-01-10T08:00:00Z',
    updated_at: '2025-01-10T08:00:00Z',
  },
  {
    id: 'comp-3',
    name: 'Noon',
    website_url: 'https://www.noon.com',
    search_url_pattern: 'https://www.noon.com/uae-en/search?q={query}',
    logo: '🌙',
    matching_rules: { title_similarity_threshold: 0.70, brand_match_required: true, model_match_required: false },
    price_selector: '[data-qa="product-price"]',
    screenshot_required: true,
    status: 'active',
    created_at: '2025-01-10T08:00:00Z',
    updated_at: '2025-01-10T08:00:00Z',
  },
  {
    id: 'comp-4',
    name: 'Amazon UAE',
    website_url: 'https://www.amazon.ae',
    search_url_pattern: 'https://www.amazon.ae/s?k={query}',
    logo: '📦',
    matching_rules: { title_similarity_threshold: 0.72, brand_match_required: true, model_match_required: false },
    price_selector: '.a-price .a-offscreen',
    screenshot_required: true,
    status: 'active',
    created_at: '2025-01-10T08:00:00Z',
    updated_at: '2025-01-10T08:00:00Z',
  },
  {
    id: 'comp-5',
    name: 'Carrefour UAE',
    website_url: 'https://www.carrefouruae.com',
    search_url_pattern: 'https://www.carrefouruae.com/mafuae/en/search?keyword={query}',
    logo: '🏪',
    matching_rules: { title_similarity_threshold: 0.68, brand_match_required: false, model_match_required: false },
    price_selector: '.css-price .value',
    screenshot_required: false,
    status: 'active',
    created_at: '2025-01-10T08:00:00Z',
    updated_at: '2025-01-10T08:00:00Z',
  },
  {
    id: 'comp-6',
    name: 'Emax',
    website_url: 'https://www.emaxuae.com',
    search_url_pattern: 'https://www.emaxuae.com/search?q={query}',
    logo: '⚡',
    matching_rules: { title_similarity_threshold: 0.75, brand_match_required: true, model_match_required: true },
    price_selector: '.product-price',
    screenshot_required: true,
    status: 'inactive',
    created_at: '2025-01-10T08:00:00Z',
    updated_at: '2025-01-10T08:00:00Z',
  },
]

export const mockSKUs: SKU[] = [
  {
    id: 'sku-1',
    sku_id: 'APPL-IP15P-256-BLK',
    product_name: 'Apple iPhone 15 Pro 256GB Black Titanium',
    brand: 'Apple',
    category: 'Smartphones',
    current_price: 4599,
    product_url: 'https://www.example.com/iphone-15-pro',
    target_marketplace: 'UAE',
    competitor_urls: [],
    min_price: 4200,
    max_price: 5200,
    margin_threshold: 8,
    alert_recipients: ['pricing@example.com', 'manager@example.com'],
    status: 'active',
    monitoring_frequency: 'daily',
    last_checked: '2026-04-27T06:30:00Z',
    created_at: '2025-02-01T10:00:00Z',
    updated_at: '2026-04-27T06:30:00Z',
  },
  {
    id: 'sku-2',
    sku_id: 'SAMS-GS24-256-BLK',
    product_name: 'Samsung Galaxy S24 256GB Onyx Black',
    brand: 'Samsung',
    category: 'Smartphones',
    current_price: 3299,
    product_url: 'https://www.example.com/samsung-s24',
    target_marketplace: 'UAE',
    competitor_urls: [],
    min_price: 2900,
    max_price: 3800,
    margin_threshold: 10,
    alert_recipients: ['pricing@example.com'],
    status: 'active',
    monitoring_frequency: 'daily',
    last_checked: '2026-04-27T06:31:00Z',
    created_at: '2025-02-01T10:00:00Z',
    updated_at: '2026-04-27T06:31:00Z',
  },
  {
    id: 'sku-3',
    sku_id: 'SONY-WH1000XM5-BLK',
    product_name: 'Sony WH-1000XM5 Wireless Headphones Black',
    brand: 'Sony',
    category: 'Audio',
    current_price: 1349,
    product_url: 'https://www.example.com/sony-wh1000xm5',
    target_marketplace: 'UAE',
    competitor_urls: [],
    min_price: 1100,
    max_price: 1600,
    margin_threshold: 12,
    alert_recipients: ['pricing@example.com'],
    status: 'active',
    monitoring_frequency: 'weekly',
    last_checked: '2026-04-25T08:00:00Z',
    created_at: '2025-02-01T10:00:00Z',
    updated_at: '2026-04-25T08:00:00Z',
  },
  {
    id: 'sku-4',
    sku_id: 'APPL-MBA-M3-8GB-256',
    product_name: 'Apple MacBook Air M3 8GB 256GB Space Gray',
    brand: 'Apple',
    category: 'Laptops',
    current_price: 5299,
    product_url: 'https://www.example.com/macbook-air-m3',
    target_marketplace: 'UAE',
    competitor_urls: [],
    min_price: 4900,
    max_price: 6000,
    margin_threshold: 7,
    alert_recipients: ['pricing@example.com', 'manager@example.com'],
    status: 'active',
    monitoring_frequency: 'daily',
    last_checked: '2026-04-27T06:32:00Z',
    created_at: '2025-02-01T10:00:00Z',
    updated_at: '2026-04-27T06:32:00Z',
  },
  {
    id: 'sku-5',
    sku_id: 'SONY-PS5-DISC-WHT',
    product_name: 'PlayStation 5 Disc Edition White',
    brand: 'Sony',
    category: 'Gaming',
    current_price: 2299,
    product_url: 'https://www.example.com/ps5',
    target_marketplace: 'UAE',
    competitor_urls: [],
    min_price: 2000,
    max_price: 2700,
    margin_threshold: 6,
    alert_recipients: ['pricing@example.com'],
    status: 'active',
    monitoring_frequency: 'daily',
    last_checked: '2026-04-27T06:33:00Z',
    created_at: '2025-02-01T10:00:00Z',
    updated_at: '2026-04-27T06:33:00Z',
  },
  {
    id: 'sku-6',
    sku_id: 'SAMS-QN85B-55-BLK',
    product_name: 'Samsung 55" Neo QLED QN85B Smart TV',
    brand: 'Samsung',
    category: 'Televisions',
    current_price: 4199,
    min_price: 3600,
    max_price: 4800,
    margin_threshold: 9,
    alert_recipients: ['pricing@example.com'],
    status: 'paused',
    monitoring_frequency: 'weekly',
    created_at: '2025-02-01T10:00:00Z',
    updated_at: '2026-03-15T10:00:00Z',
  },
]

export const mockAgentRuns: AgentRun[] = [
  {
    id: 'run-1',
    status: 'completed',
    triggered_by: 'scheduled',
    skus_total: 6,
    skus_processed: 6,
    competitors_checked: 28,
    mismatches_found: 4,
    alerts_sent: 3,
    screenshots_captured: 22,
    started_at: '2026-04-27T06:30:00Z',
    completed_at: '2026-04-27T06:48:00Z',
    notes: 'Daily monitoring run completed successfully.',
  },
  {
    id: 'run-2',
    status: 'completed',
    triggered_by: 'manual',
    skus_total: 5,
    skus_processed: 5,
    competitors_checked: 24,
    mismatches_found: 2,
    alerts_sent: 2,
    screenshots_captured: 18,
    started_at: '2026-04-26T14:00:00Z',
    completed_at: '2026-04-26T14:15:00Z',
  },
  {
    id: 'run-3',
    status: 'failed',
    triggered_by: 'scheduled',
    skus_total: 6,
    skus_processed: 3,
    competitors_checked: 14,
    mismatches_found: 1,
    alerts_sent: 0,
    screenshots_captured: 8,
    started_at: '2026-04-26T06:30:00Z',
    completed_at: '2026-04-26T06:39:00Z',
    error_message: 'Connection timeout on Carrefour UAE. Partial run completed.',
  },
  {
    id: 'run-4',
    status: 'completed',
    triggered_by: 'scheduled',
    skus_total: 6,
    skus_processed: 6,
    competitors_checked: 30,
    mismatches_found: 5,
    alerts_sent: 4,
    screenshots_captured: 25,
    started_at: '2026-04-25T06:30:00Z',
    completed_at: '2026-04-25T06:52:00Z',
  },
]

export const mockRecommendations: Recommendation[] = [
  {
    id: 'rec-1',
    run_id: 'run-1',
    sku_id: 'sku-1',
    sku_name: 'Apple iPhone 15 Pro 256GB Black Titanium',
    sku_brand: 'Apple',
    current_price: 4599,
    recommended_price: 4399,
    lowest_competitor_price: 4299,
    highest_competitor_price: 4699,
    avg_competitor_price: 4437,
    status: 'overpriced',
    action: 'decrease',
    price_diff: -200,
    price_diff_pct: -4.35,
    competitor_data: [
      { competitor_name: 'Noon', price: 4299, url: 'https://www.noon.com/product/iphone-15-pro' },
      { competitor_name: 'Amazon UAE', price: 4399, url: 'https://www.amazon.ae/product/iphone-15-pro' },
      { competitor_name: 'Sharaf DG', price: 4499, url: 'https://www.sharafdg.com/iphone-15-pro' },
      { competitor_name: 'Jumbo', price: 4550, url: 'https://www.jumbo.com/iphone-15-pro' },
      { competitor_name: 'Carrefour UAE', price: 4699, url: 'https://www.carrefouruae.com/iphone-15-pro' },
    ],
    reviewed: false,
    applied: false,
    created_at: '2026-04-27T06:48:00Z',
  },
  {
    id: 'rec-2',
    run_id: 'run-1',
    sku_id: 'sku-2',
    sku_name: 'Samsung Galaxy S24 256GB Onyx Black',
    sku_brand: 'Samsung',
    current_price: 3299,
    recommended_price: 3149,
    lowest_competitor_price: 3099,
    highest_competitor_price: 3349,
    avg_competitor_price: 3193,
    status: 'overpriced',
    action: 'decrease',
    price_diff: -150,
    price_diff_pct: -4.55,
    competitor_data: [
      { competitor_name: 'Amazon UAE', price: 3099, url: 'https://www.amazon.ae/samsung-s24' },
      { competitor_name: 'Noon', price: 3149, url: 'https://www.noon.com/samsung-s24' },
      { competitor_name: 'Jumbo', price: 3249, url: 'https://www.jumbo.com/samsung-s24' },
      { competitor_name: 'Sharaf DG', price: 3349, url: 'https://www.sharafdg.com/samsung-s24' },
    ],
    reviewed: true,
    applied: false,
    created_at: '2026-04-27T06:48:00Z',
  },
  {
    id: 'rec-3',
    run_id: 'run-1',
    sku_id: 'sku-3',
    sku_name: 'Sony WH-1000XM5 Wireless Headphones Black',
    sku_brand: 'Sony',
    current_price: 1349,
    recommended_price: 1349,
    lowest_competitor_price: 1299,
    highest_competitor_price: 1499,
    avg_competitor_price: 1373,
    status: 'price_ok',
    action: 'maintain',
    price_diff: 0,
    price_diff_pct: 0,
    competitor_data: [
      { competitor_name: 'Noon', price: 1299, url: 'https://www.noon.com/sony-wh1000xm5' },
      { competitor_name: 'Amazon UAE', price: 1349, url: 'https://www.amazon.ae/sony-wh1000xm5' },
      { competitor_name: 'Carrefour UAE', price: 1449, url: 'https://www.carrefouruae.com/sony-headphones' },
      { competitor_name: 'Jumbo', price: 1499, url: 'https://www.jumbo.com/sony-wh1000xm5' },
    ],
    reviewed: false,
    applied: false,
    created_at: '2026-04-27T06:48:00Z',
  },
  {
    id: 'rec-4',
    run_id: 'run-1',
    sku_id: 'sku-4',
    sku_name: 'Apple MacBook Air M3 8GB 256GB Space Gray',
    sku_brand: 'Apple',
    current_price: 5299,
    recommended_price: 5499,
    lowest_competitor_price: 5399,
    highest_competitor_price: 5799,
    avg_competitor_price: 5566,
    status: 'underpriced',
    action: 'increase',
    price_diff: 200,
    price_diff_pct: 3.77,
    competitor_data: [
      { competitor_name: 'Sharaf DG', price: 5399, url: 'https://www.sharafdg.com/macbook-air-m3' },
      { competitor_name: 'Jumbo', price: 5499, url: 'https://www.jumbo.com/macbook-air-m3' },
      { competitor_name: 'Amazon UAE', price: 5599, url: 'https://www.amazon.ae/macbook-air-m3' },
      { competitor_name: 'Noon', price: 5799, url: 'https://www.noon.com/macbook-air-m3' },
    ],
    reviewed: true,
    applied: true,
    created_at: '2026-04-27T06:48:00Z',
  },
  {
    id: 'rec-5',
    run_id: 'run-1',
    sku_id: 'sku-5',
    sku_name: 'PlayStation 5 Disc Edition White',
    sku_brand: 'Sony',
    current_price: 2299,
    recommended_price: 2299,
    lowest_competitor_price: 2199,
    highest_competitor_price: 2499,
    avg_competitor_price: 2337,
    status: 'needs_manual_review',
    action: 'manual_review',
    price_diff: 0,
    price_diff_pct: 0,
    competitor_data: [
      { competitor_name: 'Amazon UAE', price: 2199 },
      { competitor_name: 'Noon', price: 2299 },
      { competitor_name: 'Carrefour UAE', price: 2399 },
    ],
    reviewed: false,
    applied: false,
    created_at: '2026-04-27T06:48:00Z',
  },
]

export const mockCompetitorChecks: CompetitorCheck[] = [
  {
    id: 'check-1',
    run_id: 'run-1',
    sku_id: 'sku-1',
    competitor_id: 'comp-3',
    competitor_name: 'Noon',
    competitor_price: 4299,
    competitor_url: 'https://www.noon.com/product/iphone-15-pro',
    our_price: 4599,
    availability: true,
    delivery_fee: 0,
    status: 'overpriced',
    match_confidence: 0.94,
    recommended_price: 4399,
    recommendation_reason: 'Competitor Noon prices iPhone 15 Pro at AED 4,299 — 6.5% lower. Recommend reducing to AED 4,399 to stay competitive while maintaining margin.',
    screenshot_search_url: '/screenshots/check-1-search.png',
    screenshot_product_url: '/screenshots/check-1-product.png',
    email_sent: true,
    created_at: '2026-04-27T06:35:00Z',
  },
  {
    id: 'check-2',
    run_id: 'run-1',
    sku_id: 'sku-1',
    competitor_id: 'comp-4',
    competitor_name: 'Amazon UAE',
    competitor_price: 4399,
    competitor_url: 'https://www.amazon.ae/product/iphone-15-pro',
    our_price: 4599,
    availability: true,
    delivery_fee: 0,
    status: 'overpriced',
    match_confidence: 0.97,
    recommended_price: 4399,
    recommendation_reason: 'Amazon UAE lists at AED 4,399, 4.3% below our price.',
    screenshot_search_url: '/screenshots/check-2-search.png',
    screenshot_product_url: '/screenshots/check-2-product.png',
    email_sent: false,
    created_at: '2026-04-27T06:37:00Z',
  },
]

export const mockEmailAlerts: EmailAlert[] = [
  {
    id: 'alert-1',
    run_id: 'run-1',
    sku_id: 'sku-1',
    sku_name: 'Apple iPhone 15 Pro 256GB Black Titanium',
    check_id: 'check-1',
    recipient: 'pricing@example.com',
    subject: '⚠️ Price Alert: iPhone 15 Pro is overpriced vs Noon (-AED 300)',
    status: 'sent',
    sent_at: '2026-04-27T06:49:00Z',
    preview_data: {
      our_price: 4599,
      competitor_price: 4299,
      competitor_name: 'Noon',
      recommended_price: 4399,
      reason: 'Competitor pricing 6.5% lower than our current price',
    },
  },
  {
    id: 'alert-2',
    run_id: 'run-1',
    sku_id: 'sku-2',
    sku_name: 'Samsung Galaxy S24 256GB Onyx Black',
    check_id: 'check-3',
    recipient: 'pricing@example.com',
    subject: '⚠️ Price Alert: Samsung Galaxy S24 overpriced vs Amazon UAE (-AED 200)',
    status: 'sent',
    sent_at: '2026-04-27T06:49:30Z',
    preview_data: {
      our_price: 3299,
      competitor_price: 3099,
      competitor_name: 'Amazon UAE',
      recommended_price: 3149,
      reason: 'Amazon UAE undercutting by 6.1%',
    },
  },
  {
    id: 'alert-3',
    run_id: 'run-1',
    sku_id: 'sku-4',
    sku_name: 'Apple MacBook Air M3 8GB 256GB Space Gray',
    check_id: 'check-4',
    recipient: 'manager@example.com',
    subject: '📈 Opportunity: MacBook Air M3 underpriced vs market (+AED 200 potential)',
    status: 'sent',
    sent_at: '2026-04-27T06:50:00Z',
    preview_data: {
      our_price: 5299,
      competitor_price: 5399,
      competitor_name: 'Sharaf DG',
      recommended_price: 5499,
      reason: 'Market pricing supports a price increase',
    },
  },
  {
    id: 'alert-4',
    run_id: 'run-2',
    sku_id: 'sku-1',
    sku_name: 'Apple iPhone 15 Pro 256GB Black Titanium',
    check_id: 'check-5',
    recipient: 'pricing@example.com',
    subject: '⚠️ Price Alert: iPhone 15 Pro is overpriced vs Noon',
    status: 'failed',
    error_message: 'SMTP connection refused',
    preview_data: {
      our_price: 4599,
      competitor_price: 4349,
      competitor_name: 'Noon',
      recommended_price: 4449,
      reason: 'Competitor price drop detected',
    },
  },
]

export const mockAgentLogs: AgentLog[] = [
  { id: 'log-1', run_id: 'run-1', level: 'info', message: 'Agent run started. Processing 6 SKUs across 5 competitors.', timestamp: '2026-04-27T06:30:00Z' },
  { id: 'log-2', run_id: 'run-1', sku_id: 'sku-1', level: 'info', message: 'Checking SKU: Apple iPhone 15 Pro 256GB Black Titanium', timestamp: '2026-04-27T06:30:10Z' },
  { id: 'log-3', run_id: 'run-1', sku_id: 'sku-1', competitor_id: 'comp-3', level: 'info', message: 'Visiting Noon — searching for "Apple iPhone 15 Pro 256GB"', timestamp: '2026-04-27T06:30:15Z' },
  { id: 'log-4', run_id: 'run-1', sku_id: 'sku-1', competitor_id: 'comp-3', level: 'success', message: 'Found matching product on Noon. Price: AED 4,299. Confidence: 94%', timestamp: '2026-04-27T06:30:28Z' },
  { id: 'log-5', run_id: 'run-1', sku_id: 'sku-1', competitor_id: 'comp-3', level: 'info', message: 'Screenshot captured: search page and product page.', timestamp: '2026-04-27T06:30:31Z' },
  { id: 'log-6', run_id: 'run-1', sku_id: 'sku-1', competitor_id: 'comp-3', level: 'warn', message: 'Price mismatch detected! Our price AED 4,599 vs Noon AED 4,299 (-6.5%)', timestamp: '2026-04-27T06:30:32Z' },
  { id: 'log-7', run_id: 'run-1', sku_id: 'sku-1', competitor_id: 'comp-4', level: 'info', message: 'Visiting Amazon UAE — searching for "Apple iPhone 15 Pro 256GB Black Titanium"', timestamp: '2026-04-27T06:30:40Z' },
  { id: 'log-8', run_id: 'run-1', sku_id: 'sku-1', competitor_id: 'comp-4', level: 'success', message: 'Found on Amazon UAE. Price: AED 4,399. Confidence: 97%', timestamp: '2026-04-27T06:30:55Z' },
  { id: 'log-9', run_id: 'run-1', sku_id: 'sku-2', level: 'info', message: 'Checking SKU: Samsung Galaxy S24 256GB Onyx Black', timestamp: '2026-04-27T06:33:00Z' },
  { id: 'log-10', run_id: 'run-1', sku_id: 'sku-3', level: 'info', message: 'Checking SKU: Sony WH-1000XM5 Wireless Headphones', timestamp: '2026-04-27T06:37:00Z' },
  { id: 'log-11', run_id: 'run-1', sku_id: 'sku-4', level: 'success', message: 'MacBook Air M3: We are underpriced. Recommending price increase to AED 5,499.', timestamp: '2026-04-27T06:42:00Z' },
  { id: 'log-12', run_id: 'run-1', level: 'info', message: 'Generating recommendations for 6 SKUs...', timestamp: '2026-04-27T06:47:00Z' },
  { id: 'log-13', run_id: 'run-1', level: 'success', message: 'Sending 3 email alerts to configured recipients...', timestamp: '2026-04-27T06:48:30Z' },
  { id: 'log-14', run_id: 'run-1', level: 'success', message: 'Agent run completed. 4 mismatches found, 3 alerts sent.', timestamp: '2026-04-27T06:48:59Z' },
]

export const mockDashboardStats: DashboardStats = {
  total_skus: 6,
  active_competitors: 5,
  price_mismatches: 4,
  alerts_sent: 3,
  last_run: mockAgentRuns[0],
  next_run: '2026-04-28T06:30:00Z',
  recent_activity: mockAgentLogs.slice(-5),
  recent_recommendations: mockRecommendations.slice(0, 3),
}
